/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.PegawaiDAOImpl;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import model.Pegawai;

/**
 *
 * @author user
 */
public class AplikasiReservasi extends javax.swing.JFrame {

    private CheckReservasi checkReservasi;
    private FormReservasi formReservasi;
    private Report report;
    private boolean loginManager;
    private boolean loginResepsionis;
    public static Pegawai pegawai = new Pegawai();
    PegawaiDAOImpl daoPegawai = new PegawaiDAOImpl();

    public AplikasiReservasi() {
        initComponents();

        checkReservasi = new CheckReservasi();
        formReservasi = new FormReservasi();
        report = new Report();

        loginManager = false;
        loginResepsionis = false;

        this.add(checkReservasi);
        this.add(formReservasi);
        this.add(report);

        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(false);
        Login.setVisible(false);
        pemilihanLogin.setVisible(true);

        setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);

        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        About = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        pilihanManager = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        pilihanResepsionis = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        pemilihanLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Menu1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        About.setBackground(new java.awt.Color(153, 153, 255));
        About.setForeground(new java.awt.Color(153, 153, 255));
        About.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logohotel.png")));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logohotel.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 99, 0, 101);
        jPanel1.add(jLabel4, gridBagConstraints);

        jLabel5.setText("<html> Created by: <br /> Rangga Adikusuma <br /> Abi Vegari <br /> Rashona <br /><br/><blink> Beta Version 0.1</blink> </html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 142, 54, 0);
        jPanel1.add(jLabel5, gridBagConstraints);

        About.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hotel Sejahtera");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setBackground(new java.awt.Color(153, 153, 255));
        Login.setMinimumSize(new java.awt.Dimension(800, 63));
        Login.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("Username  ");
        jLabel2.setPreferredSize(new java.awt.Dimension(70, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        Login.add(jLabel2, gridBagConstraints);

        txtUsername.setText("manager");
        txtUsername.setPreferredSize(new java.awt.Dimension(150, 25));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        Login.add(txtUsername, gridBagConstraints);

        txtPass.setText("123");
        txtPass.setPreferredSize(new java.awt.Dimension(150, 25));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        Login.add(txtPass, gridBagConstraints);

        btnLogin.setBackground(new java.awt.Color(0, 255, 0));
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        Login.add(btnLogin, gridBagConstraints);

        jLabel3.setText("Password  ");
        jLabel3.setPreferredSize(new java.awt.Dimension(70, 14));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        Login.add(jLabel3, gridBagConstraints);

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setText("Back");
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setPreferredSize(new java.awt.Dimension(57, 25));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        Login.add(jButton7, gridBagConstraints);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logohotel.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        Login.add(jLabel6, gridBagConstraints);

        getContentPane().add(Login, "card3");

        pilihanManager.setBackground(new java.awt.Color(153, 153, 255));
        pilihanManager.setLayout(new java.awt.GridBagLayout());

        jPanel4.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jButton3.setBackground(new java.awt.Color(240, 230, 118));
        jButton3.setText("Check Reservasi");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPreferredSize(new java.awt.Dimension(200, 75));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        pilihanManager.add(jPanel4, gridBagConstraints);

        jPanel6.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel6.setPreferredSize(new java.awt.Dimension(200, 75));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jButton5.setBackground(new java.awt.Color(240, 230, 118));
        jButton5.setText("Reservasi");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        pilihanManager.add(jPanel6, gridBagConstraints);

        jPanel7.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel7.setPreferredSize(new java.awt.Dimension(200, 75));
        jPanel7.setLayout(new java.awt.GridLayout(1, 0));

        jButton6.setBackground(new java.awt.Color(240, 230, 118));
        jButton6.setText("View Report");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton6);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        pilihanManager.add(jPanel7, gridBagConstraints);

        getContentPane().add(pilihanManager, "card4");

        pilihanResepsionis.setBackground(new java.awt.Color(153, 153, 255));
        pilihanResepsionis.setLayout(new java.awt.GridBagLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel5.setLayout(new java.awt.GridLayout(1, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pilihanResepsionis.add(jPanel5, gridBagConstraints);

        jPanel8.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel8.setPreferredSize(new java.awt.Dimension(200, 75));
        jPanel8.setLayout(new java.awt.GridLayout(1, 0));

        jButton8.setBackground(new java.awt.Color(240, 230, 118));
        jButton8.setText("Reservasi");
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pilihanResepsionis.add(jPanel8, gridBagConstraints);

        jPanel9.setMinimumSize(new java.awt.Dimension(200, 75));
        jPanel9.setPreferredSize(new java.awt.Dimension(200, 75));
        jPanel9.setLayout(new java.awt.GridLayout(1, 0));

        jButton4.setBackground(new java.awt.Color(240, 230, 118));
        jButton4.setText("Check Reservasi");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.setPreferredSize(new java.awt.Dimension(200, 75));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        pilihanResepsionis.add(jPanel9, gridBagConstraints);

        getContentPane().add(pilihanResepsionis, "card5");

        pemilihanLogin.setBackground(new java.awt.Color(153, 153, 255));
        pemilihanLogin.setForeground(new java.awt.Color(153, 255, 153));
        pemilihanLogin.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Kylets", 1, 80)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logohotel.png"))); // NOI18N
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(202, 200));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pemilihanLogin.add(jLabel1, new java.awt.GridBagConstraints());

        jButton1.setBackground(new java.awt.Color(240, 230, 118));
        jButton1.setText("Login");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setMinimumSize(new java.awt.Dimension(233, 153));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pemilihanLogin.add(jButton1, gridBagConstraints);

        getContentPane().add(pemilihanLogin, "card2");

        jMenu1.setText("File");

        jMenuItem4.setText("Menu");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem1.setText("Logout");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        Menu1.add(jMenu1);

        jMenu2.setText("Help");

        jMenuItem3.setText("About");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        Menu1.add(jMenu2);

        setJMenuBar(Menu1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pemilihanLogin.setVisible(false);
        Login.setVisible(true);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        int tempJabatan = 0;
        boolean login = false;
        for (Pegawai pxx : daoPegawai.getAllData()) {
            if (String.valueOf(txtUsername.getText()).equalsIgnoreCase(pxx.getUsername()) && String.valueOf(txtPass.getPassword()).equals(pxx.getPassword())) {
                login = true;
                pegawai = pxx;
                tempJabatan = pxx.getIdJabatan().getIdJabatan();
                break;
            } else {
                login = false;
            }
        };
        if (login == true) {
            if (tempJabatan == 1) {
                pemilihanLogin.setVisible(false);
                Login.setVisible(false);
                pilihanManager.setVisible(true);
                checkReservasi.setVisible(false);
                formReservasi.setVisible(false);
                report.setVisible(false);
                pilihanResepsionis.setVisible(false);
                Menu1.setVisible(true);
                loginManager = true;
            } else {
                pemilihanLogin.setVisible(false);
                Login.setVisible(false);
                pilihanManager.setVisible(false);
                checkReservasi.setVisible(false);
                formReservasi.setVisible(false);
                report.setVisible(false);
                pilihanResepsionis.setVisible(true);
                Menu1.setVisible(true);
                loginResepsionis = true;
            }
        } else {
            JOptionPane.showMessageDialog(this, "User/Pasword Salah", "Warning Message", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        pemilihanLogin.setVisible(false);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(true);
        checkReservasi.reset();
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        pemilihanLogin.setVisible(false);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.reset();
        formReservasi.setVisible(true);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        pemilihanLogin.setVisible(false);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(true);
        report.reset();
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        pemilihanLogin.setVisible(false);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(true);
        checkReservasi.reset();
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        pemilihanLogin.setVisible(false);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(true);
        formReservasi.reset();
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        pemilihanLogin.setVisible(true);
        pilihanManager.setVisible(false);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(false);
        if (loginManager == true) {
            loginManager = false;
        } else if (loginResepsionis == true) {
            loginResepsionis = false;
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        pemilihanLogin.setVisible(true);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        Menu1.setVisible(true);
        if (loginManager == true && loginResepsionis == false) {
            //Menu();
            pilihanManager.setVisible(true);
            pilihanResepsionis.setVisible(false);
            pemilihanLogin.setVisible(false);

        } else if (loginManager == false && loginResepsionis == true) {
            //Menu2();
            pilihanManager.setVisible(false);
            pilihanResepsionis.setVisible(true);
            pemilihanLogin.setVisible(false);

        }
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        pemilihanLogin.setVisible(true);
        Login.setVisible(false);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        About.setSize(600, 400);
        About.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        pemilihanLogin.setVisible(false);
        Login.setVisible(true);
        checkReservasi.setVisible(false);
        formReservasi.setVisible(false);
        report.setVisible(false);
        pilihanResepsionis.setVisible(false);
        Menu1.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiReservasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiReservasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog About;
    private javax.swing.JPanel Login;
    private javax.swing.JMenuBar Menu1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel pemilihanLogin;
    private javax.swing.JPanel pilihanManager;
    private javax.swing.JPanel pilihanResepsionis;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logohotel.png")));
    }

}
