/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.CustomerDAOImpl;
import control.KamarDAOImpl;
import control.PegawaiDAOImpl;
import control.ResDetailDAOImpl;
import control.ReservasiDAOImpl;
import control.RoomDAOImpl;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Customer;
import model.Kamar;
import model.Pegawai;
import model.ResDetail;
import model.Reservasi;
import model.Room;
import org.hibernate.criterion.Projections;

/**
 *
 * @author user
 */
public class FormReservasi extends javax.swing.JPanel {

    CustomerDAOImpl daoCustomer;
    ReservasiDAOImpl daoReservasi;
    ResDetailDAOImpl daoResDetail;
    PegawaiDAOImpl daoPegawai;
    RoomDAOImpl daoRoom;
    KamarDAOImpl daoKamar;

    DefaultTableModel dtmResDetail;
    List<ResDetail> listResDetail;
    List<Reservasi> listReservasi;
    List<Room> listRoom;
    List<Pegawai> listPegawai;
    List<Customer> listCustomer;
    Customer newCustomer;
    Reservasi newReservasi;
    Pegawai newPegawai;
    Room newRoom;
    Kamar newKamar;

    DefaultComboBoxModel dcbmTipeKamar;
    DefaultComboBoxModel dcbmPegawai;

    SimpleDateFormat sdf;
    Double grandTotal;
    Double subTotal;
    String reservasi;

    /**
     * Creates new form FormReservasi
     */
    public FormReservasi() {
        initComponents();
        daoCustomer = new CustomerDAOImpl();
        daoReservasi = new ReservasiDAOImpl();
        daoResDetail = new ResDetailDAOImpl();
        daoRoom = new RoomDAOImpl();
        daoPegawai = new PegawaiDAOImpl();
        daoKamar = new KamarDAOImpl();

        listPegawai = daoPegawai.getAllPegawai();
        listCustomer = daoCustomer.getAllData();
        Date date = new Date();
        Date tommorow = new Date(date.getTime() + (1000 * 60 * 60 * 24));
        tglReservasi.setDate(date);
        tglCheckIn.setDate(date);
        tglCheckIn.setMinSelectableDate(date);
        tglCheckOut.setMinSelectableDate(tommorow);
        newCustomer = new Customer();
        newReservasi = new Reservasi();
        newKamar = new Kamar();
        newPegawai = new Pegawai();

        sdf = new SimpleDateFormat("dd MMM YYYY");

        dtmResDetail = (DefaultTableModel) tableResDetail.getModel();
        listResDetail = new ArrayList<>();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        inputKtp = new javax.swing.JTextField();
        inputNamaCust = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        inputNoTelp = new javax.swing.JTextField();
        inputEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tglReservasi = new com.toedter.calendar.JDateChooser();
        tglCheckOut = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResDetail = new javax.swing.JTable();
        btnBook = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        spinJmlKamar = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tglCheckIn = new com.toedter.calendar.JDateChooser();
        btnCancel = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        cbTipeKamar = new javax.swing.JComboBox<>();
        txtHarga = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtSubTotal = new javax.swing.JFormattedTextField();
        cbJenisKelamin = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtJumBayar = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        txtJumKembalian = new javax.swing.JFormattedTextField();
        txtIdPegawai = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtKapasitas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jLabel1.setText("No KTP");
        jLabel1.setPreferredSize(new java.awt.Dimension(75, 14));

        jLabel2.setText("Nama Customer");

        jLabel3.setText("Alamat");

        jLabel4.setText("No Telepon");

        jLabel5.setText("Email");

        jLabel6.setText("Jenis Kelamin");

        jLabel7.setText("Tipe Kamar");

        inputKtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputKtpActionPerformed(evt);
            }
        });

        inputAlamat.setColumns(20);
        inputAlamat.setRows(5);
        jScrollPane1.setViewportView(inputAlamat);

        jLabel9.setText("Tanggal Reservasi");

        jLabel10.setText("Tanggal Check-out");

        tglReservasi.setBackground(new java.awt.Color(255, 102, 102));
        tglReservasi.setEnabled(false);

        tglCheckOut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglCheckOutPropertyChange(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Order"));
        jPanel1.setLayout(new java.awt.BorderLayout());

        tableResDetail.setBackground(new java.awt.Color(153, 153, 255));
        tableResDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Order", "Tipe Kamar", "Jumlah Kamar", "Tanggal Check-in", "Tanggal Check-out"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableResDetail);
        if (tableResDetail.getColumnModel().getColumnCount() > 0) {
            tableResDetail.getColumnModel().getColumn(0).setResizable(false);
            tableResDetail.getColumnModel().getColumn(1).setResizable(false);
            tableResDetail.getColumnModel().getColumn(2).setResizable(false);
            tableResDetail.getColumnModel().getColumn(3).setResizable(false);
            tableResDetail.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        btnBook.setBackground(new java.awt.Color(240, 230, 118));
        btnBook.setText("Book");
        btnBook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel11.setText("Jumlah Kamar");

        spinJmlKamar.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel13.setText("Ruang Tersedia");

        txtStock.setEditable(false);
        txtStock.setBackground(new java.awt.Color(153, 153, 255));
        txtStock.setEnabled(false);

        jLabel14.setText("Tanggal Check-in");

        tglCheckIn.setBackground(new java.awt.Color(255, 102, 102));
        tglCheckIn.setEnabled(false);
        tglCheckIn.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tglCheckInPropertyChange(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(255, 0, 204));
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(0, 255, 0));
        btnAdd.setText("Add");
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        cbTipeKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipeKamarActionPerformed(evt);
            }
        });
        cbTipeKamar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cbTipeKamarPropertyChange(evt);
            }
        });

        txtHarga.setEditable(false);
        txtHarga.setBackground(new java.awt.Color(255, 102, 102));
        txtHarga.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHargaActionPerformed(evt);
            }
        });

        jLabel12.setText("Harga Kamar");

        jLabel15.setText("Sub Total");

        txtSubTotal.setEditable(false);
        txtSubTotal.setBackground(new java.awt.Color(255, 102, 102));

        cbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        jLabel8.setText("Pegawai");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(255, 102, 102));
        txtTotal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));

        jLabel17.setText("Total");

        btnCek.setBackground(new java.awt.Color(0, 255, 0));
        btnCek.setText("CEK");
        btnCek.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });

        jLabel16.setText("Jumlah Bayar");

        txtJumBayar.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtJumBayar.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtJumBayarPropertyChange(evt);
            }
        });
        txtJumBayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtJumBayarKeyReleased(evt);
            }
        });

        jLabel18.setText("Jumlah Kembalian");

        txtJumKembalian.setEditable(false);
        txtJumKembalian.setBackground(new java.awt.Color(255, 102, 102));
        txtJumKembalian.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat(""))));
        txtJumKembalian.setEnabled(false);

        txtIdPegawai.setEditable(false);
        txtIdPegawai.setBackground(new java.awt.Color(255, 102, 102));

        jLabel19.setText("Kapasitas");

        txtKapasitas.setEditable(false);
        txtKapasitas.setEnabled(false);
        txtKapasitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKapasitasActionPerformed(evt);
            }
        });

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logohotel.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                            .addComponent(inputNoTelp)
                            .addComponent(inputNamaCust)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputKtp)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCek))
                            .addComponent(txtIdPegawai)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnBook, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTotal)
                            .addComponent(txtJumBayar)
                            .addComponent(txtJumKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglCheckOut, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglReservasi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tglCheckIn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSubTotal))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(spinJmlKamar, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3, jLabel4, jLabel5, jLabel6});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtIdPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputKtp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCek))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNamaCust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(32, 32, 32))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tglReservasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tglCheckIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tglCheckOut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbTipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtKapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spinJmlKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel)
                            .addComponent(btnAdd))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtJumBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtJumKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBook))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputKtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputKtpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputKtpActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        if ((int) spinJmlKamar.getValue() == 0) {
            JOptionPane.showMessageDialog(this, "Kamar tidak tersedia", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                if (listResDetail.isEmpty() && tglCheckOut.getDate() != null) {
                    //for (ResDetail rd : listResDetail) {
                    listResDetail.add(new ResDetail(
                            Integer.parseInt(spinJmlKamar.getValue().toString()),
                            Double.parseDouble(txtHarga.getValue().toString()),
                            tglCheckIn.getDate(),
                            tglCheckOut.getDate(),
                            listRoom.get(cbTipeKamar.getSelectedIndex())));
                    printOrder();
                    long difference = (tglCheckOut.getDate().getTime() - tglCheckIn.getDate().getTime());
                    int diffInDays = (int) (difference / 1000 / 60 / 60 / 24);
                    subTotal = (Integer.parseInt(spinJmlKamar.getValue().toString())
                            * (Double.parseDouble(txtHarga.getValue().toString())
                            * diffInDays));
                    txtSubTotal.setValue(subTotal);
                    grandTotal += subTotal;
                    txtTotal.setValue(grandTotal);
                    //}
                } else if (listResDetail != null && tglCheckOut.getDate() != null) {
                    boolean cek = true;
                    for (ResDetail rd : listResDetail) {
                        if (rd.getIdRoom().getJenisRoom().equals(cbTipeKamar.getSelectedItem().toString())) {
                            cek = false;
                            break;
                        }
                    }
                    if (cek) {
                        listResDetail.add(new ResDetail(
                                Integer.parseInt(spinJmlKamar.getValue().toString()),
                                Double.parseDouble(txtHarga.getValue().toString()),
                                tglCheckIn.getDate(),
                                tglCheckOut.getDate(),
                                listRoom.get(cbTipeKamar.getSelectedIndex())));
                        printOrder();
                        long difference = (tglCheckOut.getDate().getTime() - tglCheckIn.getDate().getTime());
                        int diffInDays = (int) (difference / 1000 / 60 / 60 / 24);
                        subTotal = (Integer.parseInt(spinJmlKamar.getValue().toString())
                                * (Double.parseDouble(txtHarga.getValue().toString())
                                * diffInDays));
                        txtSubTotal.setValue(subTotal);
                        grandTotal += subTotal;
                        txtTotal.setValue(grandTotal);
                    } else {
                        JOptionPane.showMessageDialog(this, "Kamar sudah dipilih 2x");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Tanggal Belum Diisi");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void cbTipeKamarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cbTipeKamarPropertyChange
        try {
            spinJmlKamar.setModel(new SpinnerNumberModel(1, 1, (int) listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom(), 1));
            txtHarga.setValue(listRoom.get(cbTipeKamar.getSelectedIndex()).getHarga());
            txtStock.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom()));
        } catch (Exception e) {
            //e.printStackTrace();
            spinJmlKamar.setModel(new SpinnerNumberModel(0, 0, 0, 0));
            txtHarga.setValue(listRoom.get(cbTipeKamar.getSelectedIndex()).getHarga());
            txtStock.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom()));
        }
    }//GEN-LAST:event_cbTipeKamarPropertyChange

    private void txtHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHargaActionPerformed

    }//GEN-LAST:event_txtHargaActionPerformed

    private void cbTipeKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipeKamarActionPerformed
        try {
            spinJmlKamar.setModel(new SpinnerNumberModel(1, 0, (int) listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom(), 1));
            txtHarga.setValue(listRoom.get(cbTipeKamar.getSelectedIndex()).getHarga());
            txtStock.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom()));
            txtSubTotal.setText("");
            txtKapasitas.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getKapasitas()) + " Orang");
        } catch (Exception e) {
            spinJmlKamar.setModel(new SpinnerNumberModel(0, 0, 0, 0));
            txtHarga.setValue(listRoom.get(cbTipeKamar.getSelectedIndex()).getHarga());
            txtStock.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getStockRoom()));
            txtSubTotal.setText("");
            txtKapasitas.setText(String.valueOf(listRoom.get(cbTipeKamar.getSelectedIndex()).getKapasitas()) + " Orang");
        }
    }//GEN-LAST:event_cbTipeKamarActionPerformed

    private void tglCheckOutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglCheckOutPropertyChange

    }//GEN-LAST:event_tglCheckOutPropertyChange

    private void tglCheckInPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tglCheckInPropertyChange

    }//GEN-LAST:event_tglCheckInPropertyChange

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        if (inputAlamat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Order GAGAL disimpan\nAlamat Customer harus diisi", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (inputNamaCust.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Order GAGAL disimpan\nNama Customer harus diisi)", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (inputNoTelp.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Order GAGAL disimpan\nNo. Telp harus diisi)", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (listResDetail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Data Reservasi GAGAL disimpan\nTidak ada yang dipilih", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (Integer.parseInt(txtJumBayar.getValue().toString()) == 0) {
            JOptionPane.showMessageDialog(this, "Data Order GAGAL disimpan\nMasukkan Jumlah Bayar terlebih dahulu", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else if (Float.parseFloat(txtJumKembalian.getValue().toString()) < 0) {
            JOptionPane.showMessageDialog(this, "Data Order GAGAL disimpan\nJumlah Kembalian harus minimal nol(0)", "Warning Message", JOptionPane.WARNING_MESSAGE);
        } else {
            boolean sama = false;
            for (Customer cxx : daoCustomer.getAllData()) {
                if (inputKtp.getText().equals(cxx.getNoKtpCustomer().toString())) {
                    sama = true;
                    break;
                } else {
                    sama = false;
                }
            };
            if (sama == false) {
                newCustomer = new Customer();
                newCustomer.setNoKtpCustomer(inputKtp.getText());
                newCustomer.setNamaCustomer(inputNamaCust.getText());
                newCustomer.setAlamatCustomer(inputAlamat.getText());
                newCustomer.setNoTelpCustomer(inputNoTelp.getText());
                newCustomer.setEmailCustomer(inputEmail.getText());
                newCustomer.setJenisKelamin(cbJenisKelamin.getSelectedItem().toString());
                daoCustomer.insertData(newCustomer);

            } else {
                newCustomer.setNoKtpCustomer(inputKtp.getText());
                newCustomer.setNamaCustomer(inputNamaCust.getText());
                newCustomer.setAlamatCustomer(inputAlamat.getText());
                newCustomer.setNoTelpCustomer(inputNoTelp.getText());
                newCustomer.setEmailCustomer(inputEmail.getText());
                newCustomer.setJenisKelamin(cbJenisKelamin.getSelectedItem().toString());
                daoCustomer.updateData(newCustomer);

            }
            newReservasi.setIdPegawai(AplikasiReservasi.pegawai);
            newReservasi.setTanggalReservasi(new Date());
            newReservasi.setNoKtpCustomer(newCustomer);
            newReservasi.setResDetailList(listResDetail);
            newReservasi.setTotal(grandTotal);
            daoResDetail.book(newReservasi);
            JOptionPane.showMessageDialog(this, "No. Reservasi anda adalah " + newReservasi.getNoReservasi().toString());
            Cancel();
            reset();
        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        Cancel();
        int cek = 0;
        for (Customer cxx : daoCustomer.getAllData()) {
            if (inputKtp.getText().equals(cxx.getNoKtpCustomer())) {
                cek = 1;
                inputNamaCust.setText(cxx.getNamaCustomer());
                inputAlamat.setText(cxx.getAlamatCustomer());
                inputEmail.setText(cxx.getEmailCustomer());
                inputNoTelp.setText(cxx.getNoTelpCustomer());
                cbJenisKelamin.setSelectedItem(cxx.getJenisKelamin());
                break;
            } else {
                cek = 0;
            }
        };
        if (inputKtp.getText().length() != 16) {
            JOptionPane.showMessageDialog(this, "No. KTP Harus 16 Digit");
        } else {
            if (cek == 1) {
                JOptionPane.showMessageDialog(this, "Data Customer Sudah Ada");
            } else {
                JOptionPane.showMessageDialog(this, "Data Customer Belum Ada");
            }
        }

    }//GEN-LAST:event_btnCekActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        Cancel();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtJumBayarPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtJumBayarPropertyChange
        try {
            txtJumKembalian.setValue(
                    Double.parseDouble(txtJumBayar.getValue().toString())
                    - grandTotal);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtJumBayarPropertyChange

    private void txtJumBayarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJumBayarKeyReleased
        try {
            txtJumKembalian.setValue(
                    Double.parseDouble(txtJumBayar.getValue().toString())
                    - grandTotal);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_txtJumBayarKeyReleased

    private void txtKapasitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKapasitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKapasitasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCek;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbJenisKelamin;
    private javax.swing.JComboBox<String> cbTipeKamar;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputKtp;
    private javax.swing.JTextField inputNamaCust;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spinJmlKamar;
    private javax.swing.JTable tableResDetail;
    private com.toedter.calendar.JDateChooser tglCheckIn;
    private com.toedter.calendar.JDateChooser tglCheckOut;
    private com.toedter.calendar.JDateChooser tglReservasi;
    private javax.swing.JFormattedTextField txtHarga;
    private javax.swing.JTextField txtIdPegawai;
    private javax.swing.JFormattedTextField txtJumBayar;
    private javax.swing.JFormattedTextField txtJumKembalian;
    private javax.swing.JTextField txtKapasitas;
    private javax.swing.JTextField txtStock;
    private javax.swing.JFormattedTextField txtSubTotal;
    private javax.swing.JFormattedTextField txtTotal;
    // End of variables declaration//GEN-END:variables

    private void addModelComboTipeKamar() {
        String[] model = new String[listRoom.size()];
        for (int i = 0; i < listRoom.size(); i++) {
            model[i] = listRoom.get(i).getJenisRoom();
        }
        dcbmTipeKamar = new DefaultComboBoxModel(model);
        cbTipeKamar.setModel(dcbmTipeKamar);
    }

    private void printOrder() {
        int i = 1;
        dtmResDetail.getDataVector().removeAllElements();
        if (listResDetail.isEmpty()) {
            dtmResDetail.addRow(new Object[7]);
        } else {
            for (ResDetail rd : listResDetail) {
                dtmResDetail.addRow(new Object[]{
                    i,
                    rd.getIdRoom().getJenisRoom(),
                    rd.getQuantity(),
                    sdf.format(rd.getTanggalCheckIn()),
                    sdf.format(rd.getTanggalCheckOut())
                });
                i++;
            }
        }
    }

    public void reset() {
        inputKtp.setText(null);
        inputNamaCust.setText("");
        inputEmail.setText("");
        inputNoTelp.setText("");
        inputAlamat.setText("");
        cbJenisKelamin.setSelectedIndex(0);
        tglCheckOut.setDate(null);
        spinJmlKamar.setValue(1);
        txtStock.setText("");
        newCustomer = new Customer();
        newReservasi = new Reservasi();
        newPegawai = new Pegawai();
        grandTotal = 0.0;
        subTotal = 0.0;
        txtSubTotal.setValue(subTotal);
        txtTotal.setValue(grandTotal);
        txtJumBayar.setValue(0);
        listRoom = daoRoom.getAllData();
        printOrder();
        addModelComboTipeKamar();
        cbTipeKamar.setSelectedIndex(0);
        txtIdPegawai.setText(AplikasiReservasi.pegawai.toString());
    }

    private void Cancel() {
        tglCheckOut.setDate(null);
        spinJmlKamar.setValue(1);
        txtStock.setText("");
        txtSubTotal.setText("0");
        grandTotal = 0.0;
        subTotal = 0.0;
        txtTotal.setText("0");
        listResDetail.clear();
        dtmResDetail.getDataVector().removeAllElements();
        printOrder();
        addModelComboTipeKamar();
    }
}
