/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ResDetailDAOImpl;
import control.ReservasiDAOImpl;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.ResDetail;
import model.Reservasi;

/**
 *
 * @author user
 */
public class Report extends javax.swing.JPanel implements ListSelectionListener {

    ReservasiDAOImpl daoReservasi = new ReservasiDAOImpl();
    ResDetailDAOImpl daoResDetail = new ResDetailDAOImpl();

    Reservasi rx = new Reservasi();
    ResDetail rdx = new ResDetail();

    DefaultTableModel dtmReservasi;
    DefaultTableModel dtmResDetail;

    public Report() {
        initComponents();
        dtmReservasi = (DefaultTableModel) tabelReservasi.getModel();
        dtmResDetail = (DefaultTableModel) tabelResDetail.getModel();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelReservasi = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelResDetail = new javax.swing.JTable();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(507, 430));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        btnDelete.setBackground(new java.awt.Color(255, 51, 51));
        btnDelete.setText("Delete");
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/logohotel_mini.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 514, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new java.awt.Color(153, 153, 255));
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 600));

        tabelReservasi.setBackground(new java.awt.Color(153, 153, 255));
        tabelReservasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No Reservasi", "Tanggal Reservasi", "No KTP Customer", "Total", "ID Pegawai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelReservasi);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel4, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jScrollPane3.setBackground(new java.awt.Color(153, 153, 255));

        tabelResDetail.setBackground(new java.awt.Color(153, 153, 255));
        tabelResDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipe Kamar", "Jumlah Kamar", "Tanggal Check-In", "Tanggal Check-Out", "Status Reservasi"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelResDetail);
        if (tabelResDetail.getColumnModel().getColumnCount() > 0) {
            tabelResDetail.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel2.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if (JOptionPane.showConfirmDialog(this, "Apakah yakin ingin mendelete Reservasi terpilih?", "Confirmation Delete Supplier", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE) == JOptionPane.OK_OPTION) {
            if (daoReservasi.deleteData(rx)) {
                JOptionPane.showMessageDialog(this, "Data Reservasi berhasil di delete!");
                reset();
            } else {
                JOptionPane.showMessageDialog(this, "Data Reservasi gagal di delete!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Data Reservasi batal di delete!");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelResDetail;
    private javax.swing.JTable tabelReservasi;
    // End of variables declaration//GEN-END:variables

    private void printData() {
        tabelReservasi.getSelectionModel().removeListSelectionListener(this);
        dtmReservasi.getDataVector().removeAllElements();
        if (daoReservasi.getAllData().isEmpty()) {
            dtmReservasi.addRow(new Object[10]);
        } else {
            for (Reservasi rxx : daoReservasi.getAllData()) {
                dtmReservasi.addRow(new Object[]{
                    rxx.getNoReservasi(),
                    rxx.getTanggalReservasi(),
                    rxx.getNoKtpCustomer().getNoKtpCustomer(),
                    rxx.getTotal(),
                    rxx.getIdPegawai().getIdPegawai()
                });
            }
        }
        tabelReservasi.getSelectionModel().addListSelectionListener(this);
    }

    @Override
    public void valueChanged(ListSelectionEvent e) {
        if (e.getSource() == tabelReservasi.getSelectionModel()) {
            try {
                dtmResDetail.getDataVector().removeAllElements();
                rx = new Reservasi(Integer.parseInt(tabelReservasi.getValueAt(tabelReservasi.getSelectedRow(), 0).toString()));
                rx = daoReservasi.getData(rx.getNoReservasi());
                for (ResDetail rdx : rx.getResDetailList()) {
                    dtmResDetail.addRow(new Object[]{
                        rdx.getIdRoom().getJenisRoom(),
                        rdx.getQuantity(),
                        rdx.getTanggalCheckIn(),
                        rdx.getTanggalCheckOut(),
                        rdx.getStatusReservasi()
                    });;
                }
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public void reset() {
        printData();
    }
}
